const fs = require('fs');
const path = 'C:/Users/qshub/OneDrive/Desktop/PORTFOLIO/portfolio/components/SkillsSection.tsx';
let content = '';
content += '\"use client\";\n';
content += 'import React from \"react\";\n';
content += 'interface SkillCategory { title: string; skills: string[]; }\n';
content += 'const SkillsSection = () => {\n';
content += '  const skillCategories: SkillCategory[] = [\n';
content += '    { title: \"Languages\", skills: [\"Java\", \"Python\", \"JavaScript\", \"SQL\", \"C++\", \"C\"] },\n';
content += '    { title: \"Frontend & Web\", skills: [\"React.js\", \"Next.js\", \"HTML\", \"CSS\", \"Tailwind CSS\"] },\n';
content += '    { title: \"Backend & Frameworks\", skills: [\"Node.js\", \"Express.js\", \"FastAPI\"] },\n';
content += '    { title: \"Databases\", skills: [\"PostgreSQL\", \"MongoDB\", \"MySQL\"] },\n';
content += '    { title: \"Tools & Technologies\", skills: [\"Git\", \"Docker\", \"Prisma ORM\", \"VS Code\"] },\n';
content += '    { title: \"AI/ML\", skills: [\"Whisper\", \"Ollama\", \"LLM Pipelines\", \"Prompt Engineering\", \"WebSockets\"] },\n';
content += '    { title: \"Core Concepts\", skills: [\"Data Structures & Algorithms\", \"DBMS\", \"Operating Systems\", \"Computer Networks\", \"System Design\"] },\n';
content += '  ];\n';
content += '  const allSkills = skillCategories.flatMap((cat) => cat.skills);\n';
content += '  return (\n';
content += '    <section id="skills" className="w-full py-20 bg-black-100 overflow-hidden">\n';
content += '      <div className="relative z-10">\n';
content += '        <div className="mb-12 px-4"><h2 className="text-4xl md:text-5xl font-bold text-white text-center">Skills</h2></div>\n';
content += '        <div className="relative w-full overflow-hidden mb-16">\n';
content += '          <style>{\@keyframes marquee{0%{transform:translateX(0)}100%{transform:translateX(-50%)}}.marquee{display:flex;animation:marquee 40s linear infinite;width:200%}.marquee:hover{animation-play-state:paused}.marquee-content{display:flex;gap:2rem;min-width:50%;flex-shrink:0}\}</style>\n';
content += '          <div className="marquee">\n';
content += '            {allSkills.map((skill, index) => [\n';
content += '              <div key={\skill-1-\\} className="flex items-center justify-center whitespace-nowrap">\n';
content += '                <div className="px-6 py-3 bg-gradient-to-r from-cyan-500/20 to-blue-500/20 border border-cyan-500/50 rounded-full hover:border-cyan-500 transition-colors duration-300 cursor-pointer group">\n';
content += '                  <span className="text-white font-medium text-sm group-hover:text-cyan-300 transition-colors">{skill}</span>\n';
content += '                </div>\n';
content += '              </div>,\n';
content += '              <div key={\skill-2-\\} className="flex items-center justify-center whitespace-nowrap">\n';
content += '                <div className="px-6 py-3 bg-gradient-to-r from-cyan-500/20 to-blue-500/20 border border-cyan-500/50 rounded-full hover:border-cyan-500 transition-colors duration-300 cursor-pointer group">\n';
content += '                  <span className="text-white font-medium text-sm group-hover:text-cyan-300 transition-colors">{skill}</span>\n';
content += '                </div>\n';
content += '              </div>,\n';
content += '            ])}\n';
content += '          </div>\n';
content += '          <div className="absolute left-0 top-0 bottom-0 w-32 bg-gradient-to-r from-black-100 to-transparent pointer-events-none z-10" />\n';
content += '          <div className="absolute right-0 top-0 bottom-0 w-32 bg-gradient-to-l from-black-100 to-transparent pointer-events-none z-10" />\n';
content += '        </div>\n';
content += '        <div className="px-4 max-w-6xl mx-auto mt-20">\n';
content += '          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">\n';
content += '            {skillCategories.map((category, idx) => [\n';
content += '              <div key={idx} className="p-6 bg-gradient-to-br from-slate-900/50 to-slate-800/50 border border-slate-700/50 rounded-lg hover:border-cyan-500/50 transition-colors duration-300">\n';
content += '                <div className="w-full mb-4 pb-2 border-b border-slate-700/50">\n';
content += '                  <h3 className="text-xl font-semibold text-cyan-400">{category.title}</h3>\n';
content += '                </div>\n';
content += '                <div className="flex flex-wrap gap-2">\n';
content += '                  {category.skills.map((skill, idx) => ([\n';
content += '                    <span key={idx} className="px-3 py-1 text-sm bg-slate-700/50 text-slate-200 rounded-md hover:bg-cyan-500/20 hover:text-cyan-300 transition-colors">{skill}</span>,\n';
content += '                  ]))}\n';
content += '                </div>\n';
content += '              </div>,\n';
content += '            ])}\n';
content += '          </div>\n';
content += '        </div>\n';
content += '      </div>\n';
content += '    </section>\n';
content += '  );\n';
content += '};\n';
content += 'export default SkillsSection;\n';
fs.writeFileSync(path, content);
console.log('Done:', content.length, 'chars');
